project:
  env: dev # 开发环境
server:
  port: 8030 # 项目端口号
spring:
  application:
    name: alibaba-product # 项目发布名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动串
    url: jdbc:mysql://192.168.40.77:3306/v3_alibaba?serverTimezone=Asia/Shanghai # 连接串
    username: root # 连库账号
    password: root # 连库密码
    type: com.alibaba.druid.pool.DruidDataSource # Druid连接池
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.77:8848 # Nacos注册中心地址
  zipkin:
    base-url: http://192.168.40.77:9411 # Zipkin服务端地址
    discovery-client-enabled: false # 不向Nacos注册此服务
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分比设置为100%采样
mybatis:
  type-aliases-package: com.lsx.entity # 实体类别名包扫描
  configuration:
    map-underscore-to-camel-case: true # 下划线自动转驼峰
    cache-enabled: true # 开启二级缓存
    lazy-loading-enabled: true # 开启全局懒加载
    aggressive-lazy-loading: false # 关闭全局积极加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台SQL语句
dubbo:
  protocol:
    name: dubbo # 使用dubbo协议，默认
    port: -1 # 自增内部通信端口
  registry:
    address: nacos://192.168.40.77:8848 # Nacos地址
  scan:
    base-packages: com.lsx.service.impl # 包扫描@DubboService注解
seata:
  enabled: true # 启用seata
  tx-service-group: default_tx_group # 事务分组名必须和NacosConfig中的 `service.vgroupMapping.default_tx_group` 对应
  registry:
    type: nacos # 使用Nacos注册中心
    nacos:
      application: seata-server # Seata在Nacos中的服务名
      server-addr: 192.168.40.77:8848 # Nacos注册中心地址
      namespace: seata-namespace # 命名空间
      cluster: default # 集群名称
  config:
    type: nacos # 使用NacosConfig配置中心
    nacos:
      server-addr: 192.168.40.77:8848 # NacosConfig配置中心地址
      namespace: seata-namespace # 命名空间
      data-id: "seataServer.properties" # 配置文件